name: Health Signal CD

on:
  workflow_run:
    workflows: ["Health Signal CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: docker compose up -d --build
